language: php
php:
  - 7.0
sudo: false
addons:
  firefox: "53.0"
services:
  - mysql
  - memcached
before_install:
  - phpenv config-rm xdebug.ini
install:
  - composer create-project fusio/fusio fusio dev-master
  - npm install
  - node node_modules/grunt-cli/bin/grunt
  - node node_modules/protractor/bin/webdriver-manager update
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp server.php fusio/public/server.php
  - cp -r dist fusio/public/fusio/
  - cp index.htm fusio/public/fusio/index.htm
  - pushd fusio/public
  - php server.php --warmup
  - (php -S 127.0.0.1:8008 server.php) &
  - popd
  - (node node_modules/protractor/bin/webdriver-manager start > /dev/null 2>&1) &
  - sleep 8
script:
  - node node_modules/protractor/bin/protractor tests/conf.js
